{{- if eq .Values.STATUS "present" }}
  {{- if .Values.SERVICE }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.SERVICE.NAME }}
  namespace: {{ .Values.NAMESPACE }}
spec:
  type: "ClusterIP"
  ports:
    - port: 11434
      targetPort: 11434
      protocol: TCP
      name: tcp-11434
  selector:
      app: {{ .Values.SERVICE.NAME }}
  {{- end }}
{{- else }}
# Delete Service
{{- end }}
